[[main]]
  identifier = "docs"
  name = "Docs"
  url = "docs"
  weight = 1

[[main]]
  identifier = "releases"
  name = "Releases"
  url = "releases"
  weight = 2

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 3

[[main]]
  identifier = "community"
  name = "Community"
  url = "community"
  weight = 4
